---
version: "2"
checks:
  method-complexity:
    config:
      threshold: 6
  method-lines:
    enabled: false
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/
- lib/rails/generators/mobility/templates/
