module Mobility
  module Sequel
=begin

Module included in translation class dynamically generated by
{Backends::Sequel::Table} backend.

=end
    module ModelTranslation
      def self.included(base)
        base.plugin :validation_helpers
      end

      def validate
        super
        validates_presence [:locale]
      end
    end
  end
end
