name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.feature }} ruby-${{ matrix.ruby }} ${{ matrix.orm.name }}-${{ matrix.orm.version}} ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
        database:
          - 'sqlite3'
          - 'mysql57'
          - 'mysql80'
          - 'postgres'
        orm:
          - name: 'active_record'
            version: '7.2'
          - name: 'active_record'
            version: '8.0'
          - name: 'active_record'
            version: '8.1'
          - name: 'sequel'
            version: '5'
        experimental: [false]
        feature: ['unit']

        include:
          # rails/sqlite3/active_record-7.2
          - ruby: '4.0'
            feature: 'rails'
            orm:
              name: 'active_record'
              version: '7.2'
            database: 'sqlite3'
            experimental: false
          - ruby: '3.4'
            feature: 'rails'
            orm:
              name: 'active_record'
              version: '7.2'
            database: 'sqlite3'
            experimental: false
          - ruby: '3.3'
            feature: 'rails'
            orm:
              name: 'active_record'
              version: '7.2'
            database: 'sqlite3'
            experimental: false
          - ruby: '3.2'
            feature: 'rails'
            orm:
              name: 'active_record'
              version: '7.2'
            database: 'sqlite3'
            experimental: false

          # i18n fallbacks
          - ruby: '4.0'
            feature: 'i18n_fallbacks'
            experimental: false
          - ruby: '3.4'
            feature: 'i18n_fallbacks'
            experimental: false
          - ruby: '3.3'
            feature: 'i18n_fallbacks'
            experimental: false
          - ruby: '3.2'
            feature: 'i18n_fallbacks'
            experimental: false

          # Performance tests
          - ruby: '4.0'
            feature: 'performance'
            experimental: false
          - ruby: '3.4'
            feature: 'performance'
            experimental: false
          - ruby: '3.3'
            feature: 'performance'
            experimental: false
          - ruby: '3.2'
            feature: 'performance'
            experimental: false

          # Unit tests
          - ruby: '4.0'
            feature: 'unit'
            orm:
            experimental: false
          - ruby: '3.4'
            feature: 'unit'
            orm:
            experimental: false
          - ruby: '3.3'
            feature: 'unit'
            orm:
            experimental: false
          - ruby: '3.2'
            feature: 'unit'
            orm:
            experimental: false
        exclude:
          - ruby: '3.2'
            database: 'sqlite3'
            orm:
              name: 'active_record'
              version: '8.1'
          - ruby: '3.2'
            database: 'mysql57'
            orm:
              name: 'active_record'
              version: '8.1'
          - ruby: '3.2'
            database: 'mysql80'
            orm:
              name: 'active_record'
              version: '8.1'
          - ruby: '3.2'
            database: 'postgres'
            orm:
              name: 'active_record'
              version: '8.1'

    env:
      DB: ${{ matrix.database }}
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      ORM: ${{ matrix.orm.name }}
      ORM_VERSION: ${{ matrix.orm.version }}
      MYSQL57_HOST: 127.0.0.1
      MYSQL57_PORT: 3306
      MYSQL80_HOST: 127.0.0.1
      MYSQL80_PORT: 3307
      MYSQL_PASSWORD: root
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      RAILS_ENV: test
      FEATURE: ${{ matrix.feature }}

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql57:
        image: mysql:5.7
        ports: ["3306:3306"]
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: root

      mysql80:
        image: mysql:8.0
        ports: ["3307:3306"]
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update packages
        run: sudo apt-get update
      - name: Install Sqlite
        run: sudo apt-get install libsqlite3-dev -y
        if: matrix.database == 'sqlite3'
      - name: Install Postgres
        run: sudo apt-get install libpq-dev postgresql-client -y
        if: matrix.database == 'postgres'
      - name: Install MySQL client
        run: sudo apt-get install default-mysql-client -y
        if: startsWith(matrix.database, 'mysql')
      - id: cache-bundler
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ matrix.ruby }}-${{ matrix.orm.name }}-${{ matrix.orm.version }}-${{ matrix.feature }}-${{ hashFiles('mobility.gemspec') }}-${{ hashFiles('Gemfile') }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install latest Bundler
        run: gem install bundler --no-document
      - name: Install dependencies
        run: bundle install
      - name: Setup test db
        run: bundle exec rake db:create db:up
        if: matrix.database
      - name: Run tests
        run: bundle exec rake
